config/routes.rb
Rails.application.routes.draw do

# For details on the DSL available within this file, see http
   #deviseの設定
  devise_for :users

 	#home_controllerのルーティング
  root 'home#top'

  get '/home/about' => 'home#about', as: 'about'

  #users_controllerのルーティング
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  #stories_controller,favorites_controller.story_comments_controllerのルーティング
  resources :stories do
  	resource :favorites, only: [:create, :destroy]
  	resource :story_comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :story, counter_cache: :favorites_count
end

app/models/story.rb
class Story < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :story_comments, dependent: :destroy

	validates :short_story, presence: true, length: { maximum: 1250 }
	validates :title, presence: true, length: { maximum: 50 }
	validates :category, presence: true

	attachment :cover_image
	attachment :spine_cover_image

	def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
    end
end

app/models/story_comment.rb
class StoryComment < ApplicationRecord
	belongs_to :user
	belongs_to :story
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :favorite_stories, through: :favorites, source: :story, dependent: :destroy
  has_many :story_comments, dependent: :destroy
  has_many :stories, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: { in: 2..20 }
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resourse)
      user_path(current_user)
  end

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def create
		@story = Story.find(params[:story_id])
		@favorite = current_user.favorites.build(story_id: params[:story_id])
    	@favorite.save

	end

	def destroy
		@story = Story.find(params[:story_id])
		@favorite = Favorite.find_by(story_id: @story, user_id: current_user.id)
    	@favorite.destroy

	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

	before_action :authenticate_user!, only: [:new,:edit]

	def new
		@story = Story.new

	end

	def create
		@story = Story.new(story_params)
		@story.user_id = current_user.id
		@user = current_user
		if @story.save
			flash[:notice] = "小説を新規投稿しました"
			redirect_to user_path(current_user)
		else
		   render "new"

		end
	end


	def index
		#kaminariの書き方＋投稿を新しい順に並べるため
		@stories = Story.page(params[:page]).reverse_order.per(3)
		# 検索オブジェクト
    	@search = @stories.ransack(params[:q])
    	# 検索結果
    	@result = @search.result
    	# お気に入り小説
    	@all_ranks = Story.find(Favorite.group(:story_id).order('count(story_id) desc').limit(3).pluck(:story_id))

    	@story = @result.page(params[:page]).reverse_order.per(3)

	end

	def show
		@story = Story.find(params[:id])
		@story_comment = StoryComment.new
		#25文字ずつで区切り、11行埋めたら次のページを生成
		@contents = @story.short_story.scan(/.{1,25}/).each_slice(11).map(&:join)
		#@contents = @story.short_story.each_char.each_slice(210).map(&:join)
		@user = current_user
		@comments = @story.story_comments.page(params[:page]).reverse_order.per(5)
	end

	def edit
		@story = Story.find(params[:id])
		if current_user.id != @story.user.id
		   redirect_to stories_path
		end

	end

	def update
		 @story = Story.find(params[:id])
		 @user = current_user

         if @story.update(story_params)
      		flash[:notice] = "小説を更新しました"
      		redirect_to user_path(@user.id)
    	 else
      		render 'edit'
    	 end

	end

	def destroy
		@stories = Story.find(params[:id])
        @stories.destroy
        @user = current_user
        redirect_to user_path(current_user.id)

	end

	private

  	def story_params
  	  	params.require(:story).permit(:title, :category, :short_story, :cover_image, :spine_cover_image, user_attributes:[:id,:name])
  	end

  	def search_params
  		params.require(:q).permit!
  	end

end

app/controllers/story_comments_controller.rb
class StoryCommentsController < ApplicationController


	def create
		story = Story.find(params[:story_id])
        comment = current_user.story_comments.new(story_comment_params)
        comment.story_id = story.id
        comment.save
        redirect_to story_path(story)

	end

	def destroy
		comment = StoryComment.find(params[:story_id])
		story = Story.find(comment.story_id)
		comment.destroy
		redirect_to story_path(story)

	end

	private
	def story_comment_params
      params.require(:story_comment).permit(:user_id, :story_id, :comment)

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  before_action :authenticate_user!, only: [:index, :edit]


  def index
    #kaminariのページネーション
    @users = User.page(params[:page]).per(5)
    # 検索オブジェクト
    @search = @users.ransack(params[:q])
    # 検索結果
    @result = @search.result

    @users_result = @result.page(params[:page]).per(5)
    @user = current_user
    if current_user.admin_flag != 1
       redirect_to stories_path
    end

  end

  def show
  	@user =User.find(params[:id])
    #投稿小説を新しい順番に並び替えるため(.reverse_order)
    @stories = @user.stories.page(params[:stories_page]).reverse_order.per(3)
    #お気に入りした小説を新しい順番に並び替えるため。(.reverse_order)
    @favorites = @user.favorites.page(params[:favorites_page]).reverse_order.per(3)
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to stories_path
    end
  end

  def update
     @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "プロフィール更新しました"
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path

  end

  def user_params
    params.require(:user).permit(:id, :email, :name, :url, :profile_image, story_attributes:[:title])
  end

  def search_params
      params.require(:q).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/story_comments_helper.rb
module StoryCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @story.id %>').html("<%= j(render partial: 'stories/favorite', locals: {story: @story}) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @story.id %>').html("<%= j(render partial: 'stories/favorite', locals: {story: @story}) %>");

app/views/home/top.html.erb
<div class="shutter"></div>
<div class=container-fluid>
  <div class="top-image">
  	<div class="row">
  		<div class="col-5 offset-1">
  			<div class="d-flex justify-content-center">
  				<div class="top">
  					<h3 class="top-title">
  						liefeへようこそ
  					</h3>
  					<div class="btn-wrapper">
          		<div class="row">
          			<div class="col-12">
          				<div class="d-flex justify-content-center">
          					<%= link_to "小説一覧",stories_path, class: "btn-circle-fishy" %>
          				</div>
          			</div>
         			</div>
         			<div class="row">
         				<div class="col-lg-6 col-sm-6 col-xs-12">
         					<div class="d-flex justify-content-center">
         						<%= link_to "ログイン",new_user_session_path,  class: "btn-circle-fishy" %>
         					</div>
         				</div>
         				<div class="col-lg-6 col-sm-6 col-xs-12">
         					<div class="d-flex justify-content-center">
         						<%= link_to "会員登録",new_user_registration_path,  class: "btn-circle-fishy" %>
         					</div>
         				</div>
         			</div>
      			</div>
  				</div>
  			</div>
  		</div>
  	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Liefe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <!-- font-awesome導入 -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- drawer.jsの導入 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/css/drawer.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/iScroll/5.2.0/iscroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/drawer/3.2.2/js/drawer.min.js"></script>
    <!-- トースターの導入 -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <!-- cookieの導入 -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>

  </head>
  <body>
  <!--header部分 -->
    <header class="drawer drawer--right">
      <div class="container-fluid">
        <%= image_tag '/images/rogo.jpg' %>
        <button type="button" class="drawer-toggle drawer-hamburger" >
          <span class="sr-only">toggle navigation</span>
          <span class="drawer-hamburger-icon"></span>
        </button>
        <nav class="drawer-nav" style="background-color: rgba(0,0,0,0.5)">
          <ul class="drawer-manu">
            <!--ユーザーがサインインしているかで条件分岐 -->
            <% if user_signed_in? %>
              <!-- サインインしているユーザーが管理者かで条件分岐 -->
              <% if current_user.admin_flag == 1  %>
                <%= link_to "マイページ", user_path(current_user.id), class: "btn btn-header" %>
                <%= link_to "ユーザー一覧", users_path, class: "btn btn-header" %>
                <%= link_to "投稿する", new_story_path, class: "btn btn-header" %>
                <%= link_to "小説一覧", stories_path, class: "btn btn-header" %>
                <%= link_to "ログアウト",destroy_user_session_path, method: :delete, class: "btn btn-header" %>
              <!-- 管理者じゃない場合 -->
              <% else %>
                <%= link_to "マイページ", user_path(current_user.id), class: "btn btn-header" %>
                <%= link_to "投稿する", new_story_path, class: "btn btn-header" %>
                <%= link_to "小説一覧", stories_path, class: "btn btn-header" %>
                <%= link_to "ログアウト",destroy_user_session_path, method: :delete, class: "btn btn-header" %>
              <% end %>
            <!-- サインインしていない場合 -->
            <% else %>
                <%= link_to "トップページ",root_path, class: "btn btn-header"  %>
                <%= link_to "初めての方へ",about_path, class: "btn btn-header" %>
                <%= link_to "小説一覧", stories_path, class: "btn btn-header" %>
                <%= link_to "会員登録",new_user_registration_path, class: "btn btn-header" %>
                <%= link_to "ログイン",new_user_session_path, class: "btn btn-header" %>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
        <%= yield %>

  </body>
    <!-- footer部分 -->
    <footer>
      <!-- 一文字ずつ消すためにこのように書いています -->
      <div id = "footer-character">
        <span class="a">小</span>
        <span class="b">説</span>
        <span class="c">の</span>
        <span class="d">世</span>
        <span class="e">界</span>
        <span class="f">へ</span>
        <span class="g">よ</span>
        <span class="h">う</span>
        <span class="i">こ</span>
        <span class="j">そ</span>
      </div>
      <div class="rogo">
        <%= image_tag '/images/rogo.jpg' %>
      </div>
    </footer>
</html>

app/views/stories/_favorite.html.erb
<!-- ユーザーがログインしているかで条件分岐 -->
<% if user_signed_in? %>
    <!-- ログインしているユーザーがお気に入りしたかどうかで分岐 -->
    <% if story.favorited_by?(current_user) %>
        <p><%=link_to "この小説をお気に入りから解除する", story_favorites_path(story.id), method: :delete, remote: true, class: "btn btn-primary" %>
            <i class="fa fa-star" aria-hidden="true" style="color: rgb(255,255,0);"></i>
            <p>お気に入り数：<%= story.favorites.count %></p>
        </p>
    <% else %>
        <p><%=link_to "この小説をお気に入りに登録する", story_favorites_path(story.id), method: :post, remote: true, class: "btn btn-primary" %>
        	<i class="fa fa-star-o" aria-hidden="true"></i>
            <p>お気に入り数：<%= story.favorites.count %></p>
        </p>
    <% end %>
<% else %>
    <p><span>お気に入り数: </span><%= story.favorites.count %></p>
<% end %>

app/views/stories/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-6 offset-2">
			<p class="top-text">
				表紙の左端をクリックしてください<br>
				ipadでは表紙の左端をスワイプもしくはタッチしてください
			</p>
		</div>
	</div>
	<div class="row" style="margin: 20px 0 30px 0;">
		<div class="col-10 offset-1">
			<!-- 画面幅が821px以上の場合呼び出される -->
			<div id="flipbook">
				<!-- top-box1は白い背景 -->
	  			<div class="top-box1">
	  				<!-- top-box2はユーザーが投稿した画像の背景にopacityをかけたもの -->
	  				<div class="top-box2">
	  					<%= attachment_image_tag @story, :cover_image, :fill, 368, 500, fallback: "" %>
	  				</div>
	  				<!-- top-box3はタイトル、作者名を記述 -->
	  				<div class="top-box3">
			  			<p class="show-title"><%= @story.title %></p>
			  			<p class="auther">作者名：<%= link_to @story.user.name, user_path(@story.user.id), class: "auther-link" %></p>
			  		</div>
	  			</div>
			  	<% @contents.each do |content| %>
			  		<!-- text-boxは小説本文 -->
				  	<div class="text-box">
				  		<%= simple_format(content) %>
				  	</div>
			  	<% end %>
			  	<!-- end-box1は白い背景 -->
	  			<div class="end-box1">
	  				<!-- end-box2はユーザーが投稿した画像の背景にopacityをかけたもの -->
	  				<div class="end-box2">
	  					<%= attachment_image_tag @story, :spine_cover_image, :fill, 368, 500, fallback: "" %>
	  				</div>
	  			</div>
	  		</div>
	  		<!-- 画面幅が820px以下の場合に呼び出される -->
	  		<div id ="responsive-book">
	  			<h6 class="responsive-title">
	  				<%= @story.title %><br>
	  			</h6>
	  			<%= simple_format(@story.short_story) %>
	  			<h6 class="responsive-name">
	  				<%= link_to @story.user.name, user_path(@story.user.id), class: "auther-link" %>
	  			</h6>
	  		</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-3 col-xs-3">
			<!-- current_userが小説の作者と同じなら -->
			<% if current_user == @story.user %>
				<%= link_to "小説編集画面へ移動", edit_story_path(@story.id), class: "btn" %>
			<% end %>
			<!-- ユーザーがサインインしているかで条件分岐 -->
			<% if user_signed_in? %>
				<!-- current_userが管理者だったら -->
				<% if current_user.admin_flag == 1  %>
					<%= link_to "小説削除", story_path(@story.id), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn" %>
				<% end %>
			<% end %>
			<div id="favorite_buttons_<%= @story.id %>">
		        <%= render partial: 'favorite', locals: { story: @story} %>
		    </div>
		    <!--　投稿日の年、月、日で表示 -->
		    <p>投稿日：<%= @story.created_at.strftime("%Y") %>年<%= @story.created_at.strftime("%m") %>月<%= @story.created_at.strftime("%d") %>日</p>
		    <p>音量に注意してください</p>
		    <!-- 音源の再生のため -->
		    <p>current_user</p>
		    <div><%= audio_tag("/audios/sound1.mp3", :autoplay => false, :controls => true, :loop => true) %>
		 	</div>
		 	<p>涼夏</p>
		 	<div><%= audio_tag("/audios/sound2.mp3", :autoplay => false, :controls => true, :loop => true) %>
		 	</div>
		 	<p>水溜り、光</p>
		 	<div><%= audio_tag("/audios/sound3.mp3", :autoplay => false, :controls => true, :loop => true) %>
		 	</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-4 col-xs-12">
			<div class="d-flex justify-content-start">
				<h3 class="comment-count" style="margin:30px 0 10px 0 ;">
					<% if @story.story_comments.count == 0 %>
					この投稿にはまだコメントがありません。
					<% else %>
					<%= @story.story_comments.count %>件コメントがあります。
					<% end %>
				</h3>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<% if @story.story_comments.count == 0 %>
			<% else %>
			<table border="1" style="width:100%;">
				<colgroup span="1" style="width:25%;">
				<colgroup span="1" style="width:67%;">
				<colgroup span="1" style="width:8%;">
				<thead style="width:30%;">
					<tr>
					    <th>ニックネーム</th>
						<th>コメント</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @comments.each do |story_comment| %>
						<tr>
							<td><%= story_comment.user.name %></td>
							<td><%= story_comment.comment %></td>
							<td>
								<!-- current_userがコメントをしたユーザーなら -->
								<% if current_user == story_comment.user %>
									<%= link_to "コメントを削除", story_story_comments_path(story_comment.id), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn" %>
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
			<% end %>
			<%= paginate @comments, :window => 2 %>
		</div>
	</div>
	<!-- 管理者は他人のコメントを消すことができるようにするため管理者のみ表示 -->
	<% if user_signed_in? %>
		<% if current_user.admin_flag == 1 %>
			<div class="row">
				<div class="col-12">
					<p>管理者用コメント欄</p>
					<% if @story.story_comments.count == 0 %>
					<% else %>
					<table border="1" style="width:100%;">
						<colgroup span="1" style="width:25%;">
						<colgroup span="1" style="width:67%;">
						<colgroup span="1" style="width:8%;">
						<thead style="width:30%;">
							<tr>
							    <th>ニックネーム</th>
								<th>コメント</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<% @comments.each do |story_comment| %>
								<tr>
									<td><%= story_comment.user.name %></td>
									<td><%= story_comment.comment %></td>
									<td><%= link_to "コメントを削除", story_story_comments_path(story_comment.id), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-secondary" %>
									</td>
								</tr>
							<% end %>
						</tbody>
					</table>
					<%= paginate @comments, :window => 2 %>
					<% end %>
				</div>
		    </div>
		<% end %>
	<% end %>
	<!-- ユーザーがサインインしているかで条件分岐 -->
	<% if user_signed_in? %>
		<% if current_user == @story.user %>
		<% else %>
			<div class="row" style="margin-top: 40px;">
				<div class="col-lg-3 col-xs-12">
					<div class="d-flex justify-content-start">
						<h3>コメント入力欄</h3>
					</div>
				</div>
			</div>
			<div class="row" style="margin-bottom: 20px;">
				<div class="col-12">
					<%= form_for [@story, @story_comment] do |f| %>
						<%= f.text_area :comment, rows: '5', class: "form-control",placeholder:"コメントはここに" %>
	            		<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
					<% end %>
				</div>
			</div>
		<% end %>
	<% end %>
	<div class="row">
		<div class="col-6">
			<%= link_to "小説一覧へ戻る", stories_path, class: "btn btn-primary" %>
		</div>
		<div class="col-6">
			<div class="d-flex justify-content-end">
				<span id="top-btn">ページトップへ戻る</span>
			</div>
		</div>
	</div>
</div>
<!-- turn.jsの使用のため -->
<script>
  $(function(){
  	 $('#flipbook').turn({
  		elevation: 50,
  		gradients: true,
 		autoCenter: false,
 		direction: 'rtl'
  	 });
  });
</script>

app/views/users/show.html.erb
<div class="container-fluid">
<%= flash[:notice] %>
	<div class="row">
		<div class="col-lg-12 col-xs-12">
			<div class="d-flex justify-content-center">
				<h2 style="margin: 20px 0;"><%= @user.name %>のマイページ</h2>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-4 offset-lg-1 col-xs-12">
			<div class="d-flex justify-content-center">
				<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: '/images/no_image.jpg', class: "show-image" %>
			</div>
		</div>
		<div class="col-lg-6 col-xs-12">
			<div class="d-flex justify-content-center">
				<table style="margin-top: 30px;">
					<thead></thead>
					<tbody>
						<tr>
							<td style="font-size: 22px;">ペンネーム</td>
							<td></td>
							<td style="font-size: 22px;">　<%= @user.name %></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
		<!-- もしユーザーがurlを登録してなかったら -->
		<% if @user.url.blank? %>
		<!-- 何も表示しない -->
		<!--登録していたら下記を表示 -->
		<% else %>
		<div class="col-lg-6 offset-lg-6 col-xs-12">
			<div class="d-flex justify-content-center">
				<a href="<%= @user.url %>" target="_blank"><%= @user.name %>のその他URL</a>
			</div>
		</div>
		<% end %>
		<div class="col-lg-6 offset-lg-6 col-xs-12">
			<div class="d-flex justify-content-center">
				<table style="margin-top: 30px;">
					<thead></thead>
					<tbody>
						<tr>
							<!-- ユーザーがサインインしているかで条件分岐 -->
							<% if user_signed_in? %>
								<!-- マイページで表示しているユーザーがcurrent_userなら -->
								<% if @user.id == current_user.id %>
							        <td>
									<%= link_to "プロフィール編集画面へ", edit_user_path(current_user.id), class: "btn btn-primary" %></td>
									<% end %>
									<!--　current_userが管理者なら -->
									<% if current_user.admin_flag == 1  %>
									<td>
									<%= link_to "ユーザー削除", user_path(@user.id), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-secondary" %></td>
									<% end %>
								<% end %>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-10 offset-lg-1 col-xs-12">
			<div class="d-flex justify-content-start">
				<h2 style="margin: 20px 0"> 投稿小説一覧</h2>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-10 offset-lg-1 col-xs-12">
			<div class="d-flex justify-content-center">
				<!-- 投稿小説がなかった場合呼び出される -->
				<% if @stories.blank? %>
					<p><%= @user.name %>さんの投稿小説がありません<br>
						<!-- ユーザーがサインインしてイいたら -->
						 <% if user_signed_in? %>
						    <!-- サインインしているユーザーがcurrent_userなら -->
							<% if @user.id == current_user.id %>
								あなたも小説を投稿してみませんか<br>
									<%= link_to "小説投稿画面へ", new_story_path, class: "btn btn-primary" %>
							<% end %>
						<% end %>
				<% else %>
			     	<table class="table table-striped">
						<thead>
							<th>作品名</th>
							<th>ジャンル</th>
							<th>お気に入り数</th>
							<th></th>
							<th></th>
						</thead>
						<tbody>
							<% @stories.each do |story| %>
								<tr>
									<td><%= link_to story.title,story_path(story.id) %></td>
									<td><%= story.category %></td>
									<% if story.favorites_count == nil %>
									<td>0</td>
									<% else %>
									<td><%= story.favorites_count %></td>
									<% end %>
										<!--ユーザーがサインインしていたら -->
										<% if user_signed_in? %>
											<!-- サインインしているユーザーがcurrent_userだったら -->
											<% if @user.id == current_user.id %>
												<td><%= link_to "編集", edit_story_path(story.id), class: "btn btn-primary" %></td>
												<td><%= link_to "削除",story_path(story.id), method: :delete, data: {confirm: "本当に消しますか？"}, class: "btn btn-secondary" %></td>
											<% end %>
										<% end %>
							   	</tr>
							<% end %>
						</tbody>
					</table>
				<% end %>
		    </div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-4 offset-lg-1 col-xs-12">
			<%= paginate @stories, :window => 2, :param_name => 'stories_page', class: "paginate" %>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-10 offset-lg-1 col-xs-12">
			<div class="d-flex justify-content-start">
				<h2>お気に入り小説</h2>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-10 offset-lg-1 col-xs-12">
			<div class="d-flex justify-content-center">
				<% if @favorites.blank? %>
					<%= @user.name %>さんのお気に入り小説はありません
				<% else %>
		     		<table class="table table-striped">
						<thead>
							<th>作品名</th>
							<th>作者名</th>
						</thead>
						<tbody>
							<% @favorites.each do |favorite| %>
								<tr>
								<td><%= link_to favorite.story.title, story_path(favorite.story.id) %></td>
								<td><%= link_to favorite.story.user.name, user_path(favorite.story.user.id) %></td>
							    </tr>
							<% end %>
						</tbody>
					</table>
				<% end %>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-4 offset-lg-1 col-xs-12">
			<%= paginate @favorites, :window => 2, :param_name => 'favorites_page', class: "paginate" %>
		</div>
	</div>
</div>